/*
 * CustomerAddInterFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.view;

import com.dao.CustomerUserDao;
import com.dao.ProductChosenDao;
import com.model.Customer;
import com.util.Dbutil;
import com.util.StringUtil;

import javax.swing.*;
import java.sql.Connection;
import java.sql.ResultSet;


/**
 * @author __USER__
 */
public class CustomerAddInterFrm extends JInternalFrame {

    Dbutil dbutil = new Dbutil();
    CustomerUserDao customerUserDao = new CustomerUserDao();
    ProductChosenDao productChosenDao = new ProductChosenDao();

    /**
     * Creates new form CustomerAddInterFrm
     */
    public CustomerAddInterFrm() {
        initComponents();
        this.setLocation(200, 100);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    //GEN-BEGIN:initComponents
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new JLabel();
        userNameTxt = new JTextField();
        jLabel2 = new JLabel();
        password1Txt = new JPasswordField();
        jLabel3 = new JLabel();
        password2Txt = new JPasswordField();
        jLabel4 = new JLabel();
        moneyTxt = new JTextField();
        jb_Add = new JButton();
        jLabel5 = new JLabel();

        jLabel1.setText("�û���");

        jLabel2.setText("����");

        jLabel3.setText("�ٴ���������");

        jLabel4.setText("������");

        jb_Add.setText("�ύ");
        jb_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_AddActionPerformed(evt);
            }
        });
        setClosable(true);
        jLabel5.setFont(new java.awt.Font("΢���ź�", 0, 24));
        jLabel5.setText("ע���»�Ա");

        GroupLayout layout = new GroupLayout(
                getContentPane());
        getContentPane().setLayout(layout);
        layout
                .setHorizontalGroup(layout
                        .createParallelGroup(
                                GroupLayout.Alignment.LEADING)
                        .addGroup(
                                layout
                                        .createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addGroup(
                                                layout
                                                        .createParallelGroup(
                                                                GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel4))
                                        .addGap(35, 35, 35)
                                        .addGroup(
                                                layout
                                                        .createParallelGroup(
                                                                GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(jLabel5)
                                                        .addComponent(
                                                                password1Txt)
                                                        .addComponent(
                                                                userNameTxt,
                                                                GroupLayout.DEFAULT_SIZE,
                                                                167,
                                                                Short.MAX_VALUE)
                                                        .addComponent(
                                                                password2Txt)
                                                        .addGroup(
                                                                layout
                                                                        .createParallelGroup(
                                                                                GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(
                                                                                jb_Add)
                                                                        .addComponent(
                                                                                moneyTxt,
                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                84,
                                                                                GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap(88, Short.MAX_VALUE)));
        layout
                .setVerticalGroup(layout
                        .createParallelGroup(
                                GroupLayout.Alignment.LEADING)
                        .addGroup(
                                GroupLayout.Alignment.TRAILING,
                                layout
                                        .createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(
                                                jLabel5,
                                                GroupLayout.DEFAULT_SIZE,
                                                38, Short.MAX_VALUE)
                                        .addPreferredGap(
                                                LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(
                                                layout
                                                        .createParallelGroup(
                                                                GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(
                                                                userNameTxt,
                                                                GroupLayout.PREFERRED_SIZE,
                                                                GroupLayout.DEFAULT_SIZE,
                                                                GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addGroup(
                                                layout
                                                        .createParallelGroup(
                                                                GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(
                                                                password1Txt,
                                                                GroupLayout.PREFERRED_SIZE,
                                                                GroupLayout.DEFAULT_SIZE,
                                                                GroupLayout.PREFERRED_SIZE))
                                        .addGap(28, 28, 28)
                                        .addGroup(
                                                layout
                                                        .createParallelGroup(
                                                                GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3)
                                                        .addComponent(
                                                                password2Txt,
                                                                GroupLayout.PREFERRED_SIZE,
                                                                GroupLayout.DEFAULT_SIZE,
                                                                GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addGroup(
                                                layout
                                                        .createParallelGroup(
                                                                GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(
                                                                moneyTxt,
                                                                GroupLayout.PREFERRED_SIZE,
                                                                GroupLayout.DEFAULT_SIZE,
                                                                GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jb_Add).addContainerGap()));

        pack();
    }// </editor-fold>
    //GEN-END:initComponents

    private void jb_AddActionPerformed(java.awt.event.ActionEvent evt) {
        String customerName = this.userNameTxt.getText();
        String password1 = new String(this.password1Txt.getPassword());
        String password2 = new String(this.password2Txt.getPassword());
        String money = this.moneyTxt.getText();
        if (StringUtil.isEmpty(customerName)) {
            JOptionPane.showMessageDialog(null, "�û�������Ϊ��");
            return;
        }
        if (StringUtil.isEmpty(password1)) {
            JOptionPane.showMessageDialog(null, "���벻��Ϊ��");
            return;
        }
        if (!password2.equals(password1)) {
            JOptionPane.showMessageDialog(null, "��������Ҫ��ͬ");
            return;
        }
        if (Float.parseFloat(money) <= 0) {
            JOptionPane.showMessageDialog(null, " �����Ǯ����Ϊ��!");
            return;
        }
        Customer customer = new Customer(customerName, password1,
                password2, Float.parseFloat(money));
        Connection con = null;
        try {
            con = dbutil.getCon();

            //�����Ƿ������ͬ���û���
            ResultSet rs = productChosenDao.customerList(con, customer);
            while (rs.next()) {
                String customerName1 = rs.getString("customerName");
                if (customerName.equals(customerName1)) {


                    JOptionPane.showMessageDialog(null, "�û����Ѵ��ڣ�");
                    return;
                }
            }
            con = dbutil.getCon();


            int addNum = customerUserDao.customerAdd(con, customer);
            if (addNum == 1) {


                JOptionPane.showMessageDialog(null, "ע��ɹ�");
                this.dispose();
            } else {


                JOptionPane.showMessageDialog(null, "ע��ʧ��");
            }


        } catch (Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "ע��ʧ��");
        } finally {
            try {
                dbutil.closeCon(con);
            } catch (Exception e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }
    }

    //GEN-BEGIN:variables
    // Variables declaration - do not modify
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JButton jb_Add;
    private JTextField moneyTxt;
    private JPasswordField password1Txt;
    private JPasswordField password2Txt;
    private JTextField userNameTxt;
    // End of variables declaration//GEN-END:variables

}