/*
 * ViewMainFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.view;

import java.awt.Container;
import java.awt.Font;

import javax.swing.UIManager;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;

/**
 *
 * @author  __USER__
 */
public class ViewMainFrm extends javax.swing.JFrame {

	/** Creates new form ViewMainFrm�����洰�� */
	public ViewMainFrm() {
		//�ı�ϵͳĬ������
		Font font = new Font("Dialog", Font.PLAIN, 12);
		java.util.Enumeration keys = UIManager.getDefaults().keys();
		while (keys.hasMoreElements()) {
			Object key = keys.nextElement();
			Object value = UIManager.get(key);
			if (value instanceof javax.swing.plaf.FontUIResource) {
				UIManager.put(key, font);
			}
		}

		initComponents();
		
		ShopPanel panel=new ShopPanel();
		Container contentPane=getContentPane(); 	
		contentPane.add(panel);
		panel. setOpaque(true); 
		
		
		//����frame������ʾ
		this.setLocationRelativeTo(null);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new JLabel();
		jb_viewProduct = new javax.swing.JButton();
		jb_ManagetLogOn = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new Font("΢���ź�", 0, 20));
		jLabel1.setText("����Ϣ���ֽ���ƽ̨");

		jb_viewProduct.setText("�����Ʒ");
		jb_viewProduct.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jb_viewProductActionPerformed(evt);
			}
		});

		jb_ManagetLogOn.setText("����Ա��¼");
		jb_ManagetLogOn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jb_ManagetLogOnActionPerformed(evt);
			}
		});

		jButton3.setText("���û�ע��");
		
	
		
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jb_viewProductActionPerformed(evt);
			}
		});
		GroupLayout layout = new GroupLayout(
				getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap(50, Short.MAX_VALUE)
					.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 301, GroupLayout.PREFERRED_SIZE)
					.addContainerGap())
				.addGroup(layout.createSequentialGroup()
					.addGap(27)
					.addComponent(jb_viewProduct)
					.addGap(57)
					.addComponent(jb_ManagetLogOn)
					.addPreferredGap(ComponentPlacement.RELATED, 623, Short.MAX_VALUE)
					.addComponent(jButton3)
					.addGap(22))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGap(29)
					.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
					.addGap(50)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jb_viewProduct)
						.addComponent(jb_ManagetLogOn)
						.addComponent(jButton3))
					.addContainerGap(87, Short.MAX_VALUE))
		);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jb_viewProductActionPerformed(java.awt.event.ActionEvent evt) {
		new FuntionMainFrm().setVisible(true);
	}

	private void jb_ManagetLogOnActionPerformed(java.awt.event.ActionEvent evt) {
		new ManagerLogOnFrm().setVisible(true);
	}

	

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton3;
	private JLabel jLabel1;
	private javax.swing.JButton jb_ManagetLogOn;
	private javax.swing.JButton jb_viewProduct;
}